export const COLORS = {
  background: '#F7F3EF',
  cardBg: '#FFFFFF',
  surfaceContainer: '#EDE8E3',
  surfaceContainerHigh: '#E4DDD6',
  surfaceVariant: '#D9D2CA',
  primary: '#5C7A6B',
  primaryDark: '#3D5C4E',
  onPrimary: '#FFFFFF',
  accent: '#C17E5A',
  onAccent: '#FFFFFF',
  textPrimary: '#2D2A26',
  textSecondary: '#7A7068',
  textFaint: '#B0A89E',
  border: '#DDD7D0',
  cardBorder: '#DDD7D0',
  borderStrong: '#C4BBB2',
  outline: '#C4BBB2',
  error: '#C0392B',
  errorBg: '#FDECEA',
  success: '#4A7C59',
  successBg: '#EAF4ED',
  successBorder: '#B7D9C2',
  successText: '#2E6B44',
  warning: '#D4892A',
  warningBg: '#FEF3E2',
  monitoringBg: '#5C7A6B',
  monitoringText: '#FFFFFF',
  recordingDot: '#E74C3C',
  navBg: '#FFFFFF',
  navBorder: '#DDD7D0',
  navActive: '#5C7A6B',
  navInactive: '#7A7068',
  ringTrack: '#EDE8E3',
  ringFill: '#5C7A6B',
  progressTrack: '#EDE8E3',
  progressFill: '#5C7A6B',
};

export const colors = {
  light: {
    primary: COLORS.primary,
    secondary: COLORS.accent,
    background: COLORS.background,
    card: COLORS.cardBg,
    surface: COLORS.surfaceContainer,
    surfaceHigh: COLORS.surfaceContainerHigh,
    text: COLORS.textPrimary,
    textSecondary: COLORS.textSecondary,
    success: COLORS.success,
    successBg: COLORS.successBg,
    successBorder: COLORS.successBorder,
    successText: COLORS.successText,
    warning: COLORS.warning,
    warningBg: COLORS.warningBg,
    danger: COLORS.error,
    dangerBg: COLORS.errorBg,
    accent: COLORS.accent,
    border: COLORS.border,
    outline: COLORS.outline ?? COLORS.borderStrong,
    onPrimary: COLORS.onPrimary,
    muted: COLORS.textFaint,
  },
  dark: {
    primary: '#A7C4B4',
    secondary: '#E3A77F',
    background: '#211E1B',
    card: '#2D2925',
    surface: '#39342F',
    surfaceHigh: '#464039',
    text: '#F4EEE7',
    textSecondary: '#D2C6BA',
    success: '#8EC79A',
    warning: '#E8B264',
    danger: '#E58478',
    accent: '#E0A37F',
    border: '#5A5149',
    outline: '#8A7D72',
    onPrimary: '#1C2B24',
    muted: '#A99D91',
  },
};

export type AppColorMode = keyof typeof colors;
