export const LIGHT_COLORS = {
  background: '#FAF9FF',
  cardBg: '#FFFFFF',
  surfaceContainer: '#F3EEFF',
  surfaceContainerHigh: '#EDE7FF',
  surfaceVariant: '#E6DDFB',
  primary: '#5B21B6',
  primaryDark: '#4C1D95',
  onPrimary: '#FFFFFF',
  accent: '#8B5CF6',
  onAccent: '#FFFFFF',
  textPrimary: '#1F2937',
  textSecondary: '#6B7280',
  textFaint: '#9CA3AF',
  border: '#E9DFFB',
  cardBorder: '#F1ECFB',
  borderStrong: '#D8C7FA',
  outline: '#C4B5FD',
  error: '#C0392B',
  errorBg: '#FDECEA',
  success: '#16A34A',
  successBg: '#F0FDF4',
  successBorder: '#BBF7D0',
  successText: '#166534',
  warning: '#D97706',
  warningBg: '#FFF7ED',
  monitoringBg: '#5B21B6',
  monitoringText: '#FFFFFF',
  recordingDot: '#E74C3C',
  navBg: '#FFFFFF',
  navBorder: '#EFE7FF',
  navActive: '#5B21B6',
  navInactive: '#6B7280',
  ringTrack: '#F3EEFF',
  ringFill: '#5B21B6',
  progressTrack: '#F3EEFF',
  progressFill: '#5B21B6',
};

export const DARK_COLORS = {
  background: '#110C1A',
  cardBg: '#1C1428',
  surfaceContainer: '#261B36',
  surfaceContainerHigh: '#332547',
  surfaceVariant: '#3D2C55',
  primary: '#A78BFA',
  primaryDark: '#C4B5FD',
  onPrimary: '#120C1C',
  accent: '#67E8F9',
  onAccent: '#07151A',
  textPrimary: '#FBF8FF',
  textSecondary: '#D8CDEE',
  textFaint: '#B7A8D0',
  border: '#44345D',
  cardBorder: '#3A2B50',
  borderStrong: '#6D5591',
  outline: '#8B73B0',
  error: '#FDA4AF',
  errorBg: '#3B1822',
  success: '#86EFAC',
  successBg: '#123622',
  successBorder: '#276749',
  successText: '#BBF7D0',
  warning: '#FDBA74',
  warningBg: '#3B2714',
  monitoringBg: '#A78BFA',
  monitoringText: '#120C1C',
  recordingDot: '#FB7185',
  navBg: '#1C1428',
  navBorder: '#3A2B50',
  navActive: '#A78BFA',
  navInactive: '#B7A8D0',
  ringTrack: '#332547',
  ringFill: '#A78BFA',
  progressTrack: '#332547',
  progressFill: '#A78BFA',
};

export const COLORS = LIGHT_COLORS;

export const colors = {
  light: {
    primary: LIGHT_COLORS.primary,
    secondary: LIGHT_COLORS.accent,
    background: LIGHT_COLORS.background,
    card: LIGHT_COLORS.cardBg,
    surface: LIGHT_COLORS.surfaceContainer,
    surfaceHigh: LIGHT_COLORS.surfaceContainerHigh,
    text: LIGHT_COLORS.textPrimary,
    textSecondary: LIGHT_COLORS.textSecondary,
    success: LIGHT_COLORS.success,
    successBg: LIGHT_COLORS.successBg,
    successBorder: LIGHT_COLORS.successBorder,
    successText: LIGHT_COLORS.successText,
    warning: LIGHT_COLORS.warning,
    warningBg: LIGHT_COLORS.warningBg,
    danger: LIGHT_COLORS.error,
    dangerBg: LIGHT_COLORS.errorBg,
    accent: LIGHT_COLORS.accent,
    border: LIGHT_COLORS.border,
    outline: LIGHT_COLORS.outline ?? LIGHT_COLORS.borderStrong,
    onPrimary: LIGHT_COLORS.onPrimary,
    muted: LIGHT_COLORS.textFaint,
    input: '#F1F5F9',
  },
  dark: {
    primary: DARK_COLORS.primary,
    secondary: DARK_COLORS.primaryDark,
    background: DARK_COLORS.background,
    card: DARK_COLORS.cardBg,
    surface: DARK_COLORS.surfaceContainer,
    surfaceHigh: DARK_COLORS.surfaceContainerHigh,
    text: DARK_COLORS.textPrimary,
    textSecondary: DARK_COLORS.textSecondary,
    success: DARK_COLORS.success,
    successBg: DARK_COLORS.successBg,
    successBorder: DARK_COLORS.successBorder,
    successText: DARK_COLORS.successText,
    warning: DARK_COLORS.warning,
    warningBg: DARK_COLORS.warningBg,
    danger: DARK_COLORS.error,
    dangerBg: DARK_COLORS.errorBg,
    accent: DARK_COLORS.accent,
    border: DARK_COLORS.border,
    outline: DARK_COLORS.outline,
    onPrimary: DARK_COLORS.onPrimary,
    muted: DARK_COLORS.textFaint,
    input: '#20172E',
  },
};

export type AppColorMode = keyof typeof colors;
