export const COLORS = {
  background: '#FAF9FF',
  cardBg: '#FFFFFF',
  surfaceContainer: '#F3EEFF',
  surfaceContainerHigh: '#EDE7FF',
  surfaceVariant: '#E6DDFB',
  primary: '#5B21B6',
  primaryDark: '#4C1D95',
  onPrimary: '#FFFFFF',
  accent: '#8B5CF6',
  onAccent: '#FFFFFF',
  textPrimary: '#1F2937',
  textSecondary: '#6B7280',
  textFaint: '#9CA3AF',
  border: '#E9DFFB',
  cardBorder: '#F1ECFB',
  borderStrong: '#D8C7FA',
  outline: '#C4B5FD',
  error: '#C0392B',
  errorBg: '#FDECEA',
  success: '#16A34A',
  successBg: '#F0FDF4',
  successBorder: '#BBF7D0',
  successText: '#166534',
  warning: '#D97706',
  warningBg: '#FFF7ED',
  monitoringBg: '#5B21B6',
  monitoringText: '#FFFFFF',
  recordingDot: '#E74C3C',
  navBg: '#FFFFFF',
  navBorder: '#EFE7FF',
  navActive: '#5B21B6',
  navInactive: '#6B7280',
  ringTrack: '#F3EEFF',
  ringFill: '#5B21B6',
  progressTrack: '#F3EEFF',
  progressFill: '#5B21B6',
};

export const colors = {
  light: {
    primary: COLORS.primary,
    secondary: COLORS.accent,
    background: COLORS.background,
    card: COLORS.cardBg,
    surface: COLORS.surfaceContainer,
    surfaceHigh: COLORS.surfaceContainerHigh,
    text: COLORS.textPrimary,
    textSecondary: COLORS.textSecondary,
    success: COLORS.success,
    successBg: COLORS.successBg,
    successBorder: COLORS.successBorder,
    successText: COLORS.successText,
    warning: COLORS.warning,
    warningBg: COLORS.warningBg,
    danger: COLORS.error,
    dangerBg: COLORS.errorBg,
    accent: COLORS.accent,
    border: COLORS.border,
    outline: COLORS.outline ?? COLORS.borderStrong,
    onPrimary: COLORS.onPrimary,
    muted: COLORS.textFaint,
  },
  dark: {
    primary: '#A78BFA',
    secondary: '#C4B5FD',
    background: '#171022',
    card: '#241733',
    surface: '#302044',
    surfaceHigh: '#3C2A57',
    text: '#F8F5FF',
    textSecondary: '#D8CDF2',
    success: '#86EFAC',
    warning: '#FDBA74',
    danger: '#FCA5A5',
    accent: '#C4B5FD',
    border: '#4B3768',
    outline: '#7C5FB2',
    onPrimary: '#1F1235',
    muted: '#B8A9D4',
  },
};

export type AppColorMode = keyof typeof colors;
