import React, { useCallback, useEffect, useState } from 'react';
import { Alert, ScrollView, Share, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import FontAwesome from '@expo/vector-icons/FontAwesome';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { deleteDoc, doc, getDoc } from 'firebase/firestore';
import { auth, db } from '../../src/config/firebase-config';
import { BorderRadius, Colors, Spacing, Typography } from '../../src/constants/theme';
import { getScoreColor, getSessionTag, reportScoreFromData, toReportDate } from '../../src/utils/reportUtils';

type SafetyFlag = {
  severity: string;
  detected: string[];
  recommendation: string;
};

type DetailReport = {
  id: string;
  date: Date;
  score: number;
  summary: string;
  strengths: string[];
  improvements: string[];
  tips: string[];
  childName?: string | null;
  tag?: string | null;
  transcript?: string;
  safetyFlag?: SafetyFlag | null;
};

const asArray = (value: unknown): string[] => (Array.isArray(value) ? value.map(String) : []);

export default function ReportDetailScreen() {
  const router = useRouter();
  const { id } = useLocalSearchParams<{ id: string }>();
  const [report, setReport] = useState<DetailReport | null>(null);
  const [loading, setLoading] = useState(true);

  const loadReport = useCallback(async () => {
    const user = auth.currentUser;
    if (!user || !id) {
      setLoading(false);
      return;
    }

    try {
      const snapshot = await getDoc(doc(db, 'users', user.uid, 'reports', id));
      if (!snapshot.exists()) {
        setReport(null);
        return;
      }
      const data = snapshot.data();
      setReport({
        id: snapshot.id,
        date: toReportDate(data.date || data.createdAt),
        score: reportScoreFromData(data),
        summary: String(data.summary || data.analysis?.impact_analysis || ''),
        strengths: asArray(data.strengths || data.analysis?.positive_notes),
        improvements: asArray(data.improvements || data.analysis?.detected_issues),
        tips: asArray(data.tips || data.suggestions || data.analysis?.suggestions),
        childName: data.childName || null,
        tag: data.tag || 'general',
        transcript: String(data.transcript || ''),
        safetyFlag: data.safetyFlag || null,
      });
    } catch (error) {
      console.error('Failed to load report detail:', error);
      setReport(null);
    } finally {
      setLoading(false);
    }
  }, [id]);

  useEffect(() => {
    loadReport();
  }, [loadReport]);

  const deleteReport = () => {
    const user = auth.currentUser;
    if (!user || !report) return;

    Alert.alert('Delete Report', 'Are you sure you want to delete this report?', [
      { text: 'Cancel', style: 'cancel' },
      {
        text: 'Delete',
        style: 'destructive',
        onPress: async () => {
          await deleteDoc(doc(db, 'users', user.uid, 'reports', report.id));
          router.back();
        },
      },
    ]);
  };

  const shareReport = async () => {
    if (!report) return;
    await Share.share({
      message: `My Parenting Session Report 📊\n\nScore: ${report.score}/100\n\nStrengths:\n${report.strengths
        .map((item) => '✅ ' + item)
        .join('\n')}\n\nAreas to Improve:\n${report.improvements
        .map((item) => '🔧 ' + item)
        .join('\n')}\n\nTips:\n${report.tips
        .map((item) => '💡 ' + item)
        .join('\n')}\n\nGenerated by TalkWise App`,
    });
  };

  if (loading) {
    return (
      <View style={[styles.container, styles.centered]}>
        <Text style={styles.emptyText}>Loading report...</Text>
      </View>
    );
  }

  if (!report) {
    return (
      <View style={[styles.container, styles.centered]}>
        <Text style={styles.emptyTitle}>Report not found</Text>
        <TouchableOpacity style={styles.secondaryButton} onPress={() => router.back()}>
          <Text style={styles.secondaryButtonText}>Back</Text>
        </TouchableOpacity>
      </View>
    );
  }

  const scoreColor = getScoreColor(report.score);
  const tag = getSessionTag(report.tag);

  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      <TouchableOpacity style={styles.backButton} onPress={() => router.back()}>
        <FontAwesome name="chevron-left" size={14} color={Colors.text} />
        <Text style={styles.backText}>History</Text>
      </TouchableOpacity>

      <View style={styles.heroCard}>
        <Text style={styles.dateText}>
          {report.date.toLocaleString(undefined, {
            weekday: 'short',
            month: 'short',
            day: 'numeric',
            hour: 'numeric',
            minute: '2-digit',
          })}
        </Text>
        <View style={[styles.scoreCircle, { backgroundColor: scoreColor }]}>
          <Text style={styles.scoreText}>{report.score}</Text>
          <Text style={styles.scoreSubtext}>/100</Text>
        </View>
        <Text style={styles.summaryText}>{report.summary || 'Session completed.'}</Text>
        {report.childName ? <Text style={styles.metaText}>Child: {report.childName}</Text> : null}
        {report.safetyFlag ? (
          <View style={styles.safetyBadge}>
            <Text style={styles.safetyBadgeText}>⚠️ Safety review: {report.safetyFlag.severity}</Text>
          </View>
        ) : null}
        <View style={[styles.tagBadge, { backgroundColor: tag.color }]}>
          <Text style={styles.tagText}>{tag.icon} {tag.label}</Text>
        </View>
      </View>

      {report.safetyFlag ? (
        <View style={styles.safetyCard}>
          <Text style={styles.sectionTitle}>Safety Review</Text>
          <Text style={styles.bodyText}>{report.safetyFlag.recommendation}</Text>
          {report.safetyFlag.detected.map((item, index) => (
            <Text key={`${item}-${index}`} style={styles.safetyItem}>⚠️ {item}</Text>
          ))}
        </View>
      ) : null}

      <ReportList title="Strengths" icon="✅" items={report.strengths} empty="No strengths recorded." />
      <ReportList title="Improvements" icon="🔧" items={report.improvements} empty="No improvements recorded." />
      <ReportList title="Tips" icon="💡" items={report.tips} empty="No tips recorded." />

      {report.transcript ? (
        <View style={styles.card}>
          <Text style={styles.sectionTitle}>Transcript</Text>
          <Text style={styles.bodyText}>{report.transcript}</Text>
        </View>
      ) : null}

      <TouchableOpacity style={styles.shareButton} onPress={shareReport}>
        <Text style={styles.shareButtonText}>Share Report</Text>
      </TouchableOpacity>

      <TouchableOpacity style={styles.deleteButton} onPress={deleteReport}>
        <Text style={styles.deleteButtonText}>Delete Report</Text>
      </TouchableOpacity>
    </ScrollView>
  );
}

function ReportList({ title, icon, items, empty }: { title: string; icon: string; items: string[]; empty: string }) {
  return (
    <View style={styles.card}>
      <Text style={styles.sectionTitle}>{title}</Text>
      {items.length === 0 ? (
        <Text style={styles.emptyText}>{empty}</Text>
      ) : (
        items.map((item, index) => (
          <Text key={`${item}-${index}`} style={styles.listItem}>{icon} {item}</Text>
        ))
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: { backgroundColor: Colors.background, flex: 1 },
  content: { gap: 16, paddingBottom: Spacing.xxl, paddingHorizontal: Spacing.lg, paddingTop: 60 },
  centered: { alignItems: 'center', justifyContent: 'center', padding: 24 },
  backButton: { alignItems: 'center', flexDirection: 'row', gap: Spacing.sm },
  backText: { ...Typography.bodySmall, color: Colors.text, fontWeight: '800' },
  heroCard: {
    alignItems: 'center',
    backgroundColor: '#FFF',
    borderColor: '#E5E5E5',
    borderRadius: 20,
    borderWidth: 1,
    padding: 22,
  },
  dateText: { color: '#777', fontSize: 13, fontWeight: '700', marginBottom: 16 },
  scoreCircle: { alignItems: 'center', borderRadius: 62, height: 124, justifyContent: 'center', width: 124 },
  scoreText: { color: '#FFF', fontSize: 42, fontWeight: '900' },
  scoreSubtext: { color: '#FFF', fontSize: 13, fontWeight: '800' },
  summaryText: { color: '#000', fontSize: 16, fontWeight: '600', lineHeight: 24, marginTop: 18, textAlign: 'center' },
  metaText: { color: '#666', fontSize: 14, fontWeight: '700', marginTop: 10 },
  tagBadge: { borderRadius: BorderRadius.round, marginTop: 12, paddingHorizontal: 12, paddingVertical: 7 },
  tagText: { color: '#000', fontSize: 13, fontWeight: '800' },
  safetyBadge: {
    backgroundColor: '#FEF2F2',
    borderColor: '#FCA5A5',
    borderRadius: BorderRadius.round,
    borderWidth: 1,
    marginTop: 12,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  safetyBadgeText: { color: '#B91C1C', fontSize: 13, fontWeight: '900', textTransform: 'capitalize' },
  card: {
    backgroundColor: '#FFF',
    borderColor: '#E5E5E5',
    borderLeftColor: '#000',
    borderLeftWidth: 3,
    borderRadius: 16,
    borderWidth: 1,
    padding: 18,
  },
  safetyCard: {
    backgroundColor: '#FEF2F2',
    borderColor: '#FCA5A5',
    borderLeftColor: '#EF4444',
    borderLeftWidth: 3,
    borderRadius: 16,
    borderWidth: 1,
    padding: 18,
  },
  sectionTitle: { color: '#888', fontSize: 13, fontWeight: '900', letterSpacing: 1.4, marginBottom: 10, textTransform: 'uppercase' },
  listItem: { color: '#000', fontSize: 15, fontWeight: '600', lineHeight: 24, marginVertical: 4 },
  safetyItem: { color: '#991B1B', fontSize: 14, fontWeight: '700', lineHeight: 22, marginTop: 8 },
  bodyText: { color: '#111', fontSize: 15, lineHeight: 23 },
  emptyTitle: { ...Typography.h3, color: Colors.text, marginBottom: 12 },
  emptyText: { color: '#888', fontSize: 14, lineHeight: 22 },
  shareButton: { alignItems: 'center', backgroundColor: '#000', borderRadius: 14, paddingVertical: 15 },
  shareButtonText: { color: '#FFF', fontSize: 16, fontWeight: '900' },
  deleteButton: {
    alignItems: 'center',
    backgroundColor: '#FEF2F2',
    borderColor: '#FCA5A5',
    borderRadius: 14,
    borderWidth: 1,
    paddingVertical: 15,
  },
  deleteButtonText: { color: '#EF4444', fontSize: 16, fontWeight: '900' },
  secondaryButton: { borderColor: '#000', borderRadius: 12, borderWidth: 1, paddingHorizontal: 18, paddingVertical: 10 },
  secondaryButtonText: { color: '#000', fontWeight: '800' },
});
