import React, { useCallback, useEffect, useState } from 'react';
import { Alert, ScrollView, Share, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import FontAwesome from '@expo/vector-icons/FontAwesome';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { deleteDoc, doc, getDoc } from 'firebase/firestore';
import { auth, db } from '../../src/config/firebase-config';
import { getSessionTag, reportScoreFromData, toReportDate } from '../../src/utils/reportUtils';
import { colors } from '../../src/theme/colors';
import { radius, shadows, spacing } from '../../src/theme/spacing';
import { typeScale } from '../../src/theme/typography';
import {
  getScoreLabel,
  ImprovementsCard,
  SafetyBanner,
  ScoreRing,
  StrengthsCard,
  SummaryCard,
  TipsCard,
  type ReportSafetyFlag,
} from '../../src/components/ReportPresentation';

type DetailReport = {
  id: string;
  date: Date;
  durationSeconds?: number;
  score: number;
  summary: string;
  strengths: string[];
  improvements: string[];
  tips: string[];
  childName?: string | null;
  tag?: string | null;
  safetyFlag?: ReportSafetyFlag;
};

const asArray = (value: unknown): string[] => (Array.isArray(value) ? value.map(String) : []);

function formatDetailDate(date: Date) {
  return date.toLocaleString(undefined, {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  });
}

function formatDuration(seconds?: number) {
  if (!seconds) return '';
  const mins = Math.floor(seconds / 60);
  const secs = seconds % 60;
  return mins > 0 ? `${mins}m ${secs}s` : `${secs}s`;
}

export default function ReportDetailScreen() {
  const router = useRouter();
  const { id } = useLocalSearchParams<{ id: string }>();
  const [report, setReport] = useState<DetailReport | null>(null);
  const [loading, setLoading] = useState(true);

  const loadReport = useCallback(async () => {
    const user = auth.currentUser;
    if (!user || !id) {
      setLoading(false);
      return;
    }

    try {
      const snapshot = await getDoc(doc(db, 'users', user.uid, 'reports', id));
      if (!snapshot.exists()) {
        setReport(null);
        return;
      }
      const data = snapshot.data();
      setReport({
        id: snapshot.id,
        date: toReportDate(data.date || data.createdAt),
        durationSeconds: Number(data.durationSeconds || 0),
        score: reportScoreFromData(data),
        summary: String(data.summary || data.analysis?.impact_analysis || ''),
        strengths: asArray(data.strengths || data.analysis?.positive_notes),
        improvements: asArray(data.improvements || data.analysis?.detected_issues),
        tips: asArray(data.tips || data.suggestions || data.analysis?.suggestions),
        childName: data.childName || null,
        tag: data.tag || 'general',
        safetyFlag: data.safetyFlag || null,
      });
    } catch (error) {
      console.error('Failed to load report detail:', error);
      setReport(null);
    } finally {
      setLoading(false);
    }
  }, [id]);

  useEffect(() => {
    loadReport();
  }, [loadReport]);

  const deleteReport = () => {
    const user = auth.currentUser;
    if (!user || !report) return;

    Alert.alert('Delete Report', 'Are you sure you want to delete this report?', [
      { text: 'Cancel', style: 'cancel' },
      {
        text: 'Delete',
        style: 'destructive',
        onPress: async () => {
          await deleteDoc(doc(db, 'users', user.uid, 'reports', report.id));
          router.back();
        },
      },
    ]);
  };

  const shareReport = async () => {
    if (!report) return;
    await Share.share({
      message: `My Parenting Session Report 📊\n\nScore: ${report.score}/100\n\nStrengths:\n${report.strengths
        .map((item) => '✅ ' + item)
        .join('\n')}\n\nAreas to Improve:\n${report.improvements
        .map((item) => '🔧 ' + item)
        .join('\n')}\n\nTips:\n${report.tips.map((item) => '💡 ' + item).join('\n')}\n\nGenerated by TalkWise App`,
    });
  };

  if (loading) {
    return (
      <View style={[styles.container, styles.centered]}>
        <Text style={styles.emptyText}>Loading report...</Text>
      </View>
    );
  }

  if (!report) {
    return (
      <View style={[styles.container, styles.centered]}>
        <Text style={styles.emptyTitle}>Report not found</Text>
        <TouchableOpacity style={styles.secondaryButton} onPress={() => router.back()}>
          <Text style={styles.secondaryText}>Back</Text>
        </TouchableOpacity>
      </View>
    );
  }

  const tag = getSessionTag(report.tag);
  const duration = formatDuration(report.durationSeconds);

  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
      <View style={styles.header}>
        <TouchableOpacity style={styles.backButton} onPress={() => router.back()}>
          <FontAwesome name="chevron-left" size={15} color={colors.light.text} />
        </TouchableOpacity>
        <View style={styles.headerText}>
          <Text style={styles.title}>Session Report</Text>
          <Text style={styles.dateText}>{formatDetailDate(report.date).replace(',', ' ·')}</Text>
        </View>
      </View>

      <View style={styles.chips}>
        {report.childName ? <Text style={styles.chip}>{report.childName}</Text> : null}
        <Text style={styles.chip}>
          {tag.icon} {tag.label}
        </Text>
      </View>

      <View style={styles.scoreHero}>
        <ScoreRing score={report.score} />
        <Text style={styles.scoreLabel}>{getScoreLabel(report.score)}</Text>
      </View>

      <SafetyBanner safetyFlag={report.safetyFlag} />
      <SummaryCard summary={report.summary} />
      <StrengthsCard strengths={report.strengths} />
      <ImprovementsCard improvements={report.improvements} />
      <TipsCard tips={report.tips} />

      <View style={styles.footer}>
        <Text style={styles.footerText}>
          Session recorded on {formatDetailDate(report.date)}
          {duration ? ` · ${duration}` : ''}
        </Text>
        <Text style={styles.footerText}>Analyzed by TalkWise AI</Text>
      </View>

      <TouchableOpacity style={styles.primaryButton} onPress={shareReport}>
        <Text style={styles.primaryText}>Share Report</Text>
      </TouchableOpacity>

      <TouchableOpacity style={styles.deleteButton} onPress={deleteReport}>
        <Text style={styles.deleteText}>Delete Report</Text>
      </TouchableOpacity>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    backgroundColor: colors.light.background,
    flex: 1,
  },
  content: {
    gap: spacing.md,
    paddingBottom: 42,
    paddingHorizontal: spacing.lg,
    paddingTop: 58,
  },
  centered: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.lg,
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
  },
  backButton: {
    alignItems: 'center',
    backgroundColor: colors.light.surface,
    borderRadius: radius.full,
    height: 40,
    justifyContent: 'center',
    width: 40,
    ...shadows.card,
  },
  headerText: {
    flex: 1,
  },
  title: {
    color: colors.light.text,
    ...typeScale.h2,
  },
  dateText: {
    color: colors.light.textSecondary,
    ...typeScale.bodySmall,
    marginTop: spacing.xs,
  },
  chips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  chip: {
    backgroundColor: colors.light.surface,
    borderRadius: radius.full,
    color: colors.light.text,
    fontSize: 13,
    fontWeight: '800',
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  scoreHero: {
    alignItems: 'center',
    paddingVertical: spacing.sm,
  },
  scoreLabel: {
    color: colors.light.text,
    ...typeScale.subheading,
    fontWeight: '900',
    marginTop: spacing.sm,
  },
  footer: {
    gap: spacing.xs,
    paddingVertical: spacing.xs,
  },
  footerText: {
    color: colors.light.muted,
    ...typeScale.caption,
    fontWeight: '700',
    textAlign: 'center',
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: colors.light.primary,
    borderRadius: radius.full,
    paddingVertical: spacing.md,
    ...shadows.card,
  },
  primaryText: {
    color: colors.light.onPrimary,
    ...typeScale.button,
  },
  deleteButton: {
    alignItems: 'center',
    backgroundColor: colors.light.dangerBg,
    borderColor: colors.light.danger,
    borderRadius: radius.full,
    borderWidth: 1,
    paddingVertical: spacing.md,
  },
  deleteText: {
    color: colors.light.danger,
    ...typeScale.button,
  },
  emptyTitle: {
    color: colors.light.text,
    ...typeScale.subheading,
    marginBottom: spacing.sm,
  },
  emptyText: {
    color: colors.light.muted,
    ...typeScale.bodySmall,
    fontWeight: '700',
  },
  secondaryButton: {
    borderColor: colors.light.primary,
    borderRadius: radius.lg,
    borderWidth: 1,
    marginTop: spacing.md,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
  },
  secondaryText: {
    color: colors.light.primary,
    fontWeight: '800',
  },
});
